SGT/Controllers/StatusController.cs
using Microsoft.AspNetCore.Mvc;
using SGT.Data;
using SGT.Models.Domain;
using SGT.Models;
using Microsoft.EntityFrameworkCore;

namespace SGT.Controllers
{
    public class StatusController : Controller
    {
        private readonly MVCDbContext mVCDbContext1;

        public StatusController(MVCDbContext mVCDbContext)
        {
            mVCDbContext1 = mVCDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var status = await mVCDbContext1.Status.ToListAsync();
            return View(status);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> Add(AddStatusViewModel model)
        {
            if (ModelState.IsValid)
            {
                var Status = new Status
                {
                    Id = Guid.NewGuid(),
                    Descricao = model.Descricao,
                };
                await mVCDbContext1.Status.AddAsync(Status);
                await mVCDbContext1.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var Status = await mVCDbContext1.Status.FirstOrDefaultAsync(x => x.Id == id);

            if (Status != null)
            {
                var viewModel = new UpdateStatusViewModel
                {
                    Id = Status.Id,
                    Descricao = Status.Descricao,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateStatusViewModel model)
        {
            if (ModelState.IsValid)
            {
                var Status = await mVCDbContext1.Status.FirstOrDefaultAsync(x => x.Id == model.Id);

                if (Status != null)
                {
                    Status.Descricao = model.Descricao;

                    await mVCDbContext1.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateStatusViewModel model)
        {
            var Status = await mVCDbContext1.Status.FindAsync(model.Id);

            if (Status != null)
            {
                mVCDbContext1.Status.Remove(Status);
                await mVCDbContext1.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

SGT/Controllers/TarefasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SGT.Data;
using SGT.Models;
using SGT.Models.Domain;

namespace SGT.Controllers
{
    public class TarefasController : Controller
    {
        private readonly MVCDbContext mVCDbContext1;
        private readonly IHttpContextAccessor httpContextAccessor;

        public TarefasController(MVCDbContext mVCDbContext, IHttpContextAccessor httpContextAccessor)
        {
            mVCDbContext1 = mVCDbContext;
            this.httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var tarefas = await mVCDbContext1.Tarefas.ToListAsync();
            return View(tarefas);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> Add(AddTarefasViewModel model)
        {
            if (ModelState.IsValid)
            {
                string usuarioId = httpContextAccessor.HttpContext.Session.GetString("_UsuarioId");
                var usuario = await mVCDbContext1.Usuario.FirstOrDefaultAsync(x => x.Id.ToString() == usuarioId);
                var status = await mVCDbContext1.Status.FirstOrDefaultAsync(x => x.Descricao == TipoStatusViewModel.Pendente);
                var tarefa = new Tarefas
                {
                    Id = Guid.NewGuid(),
                    Descricao = model.Descricao,
                    DataCriacao = DateTime.Now,
                    IdUsuario = usuario.Id,
                    IdStatus = status.Id
                };
                await mVCDbContext1.Tarefas.AddAsync(tarefa);
                await mVCDbContext1.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task <IActionResult> View(Guid id)
        {
            var tarefa = await mVCDbContext1.Tarefas.FirstOrDefaultAsync(x => x.Id == id);

            if (tarefa != null)
            {
                var viewModel = new UpdateTarefasViewModel
                {
                    Id = tarefa.Id,
                    Descricao = tarefa.Descricao,
                    DataCriacao = tarefa.DataCriacao,
                    DataConclusao = tarefa.DataConclusao,
                    IdUsuario = tarefa.IdUsuario,
                    IdStatus = tarefa.IdStatus
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateTarefasViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tarefa = await mVCDbContext1.Tarefas.FirstOrDefaultAsync(x => x.Id == model.Id);

                if (tarefa != null)
                {
                    tarefa.Descricao = model.Descricao;
                    tarefa.IdUsuario = model.IdUsuario;
                    tarefa.IdStatus = model.IdStatus;

                    await mVCDbContext1.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateTarefasViewModel model)
        {
            var tarefa = await mVCDbContext1.Tarefas.FindAsync(model.Id);

            if (tarefa != null)
            {
                mVCDbContext1.Tarefas.Remove(tarefa);
                await mVCDbContext1.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ViewEmProgresso(UpdateTarefasViewModel model)
        {
            var tarefa = await mVCDbContext1.Tarefas.FindAsync(model.Id);

            if (tarefa != null)
            {
                var status = await mVCDbContext1.Status.FirstOrDefaultAsync(x => x.Descricao == TipoStatusViewModel.EmProgresso);
                tarefa.IdStatus = status.Id;
                tarefa.DataConclusao = DateTime.Now;

                await mVCDbContext1.SaveChangesAsync();
            }

            return RedirectToAction("View");
        }

        [HttpGet]
        public async Task<IActionResult> ViewConcluir(UpdateTarefasViewModel model)
        {
            var tarefa = await mVCDbContext1.Tarefas.FindAsync(model.Id);

            if (tarefa != null)
            {
                var status = await mVCDbContext1.Status.FirstOrDefaultAsync(x => x.Descricao == TipoStatusViewModel.Concluido);
                tarefa.IdStatus = status.Id;

                await mVCDbContext1.SaveChangesAsync();
            }

            return RedirectToAction("View");
        }
    }
}

SGT/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using SGT.Data;
using SGT.Models;
using Microsoft.EntityFrameworkCore;
using SGT.Models.Domain;

namespace SGT.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly MVCDbContext mVCDbContext1;

        public UsuarioController(MVCDbContext mVCDbContext)
        {
            mVCDbContext1 = mVCDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var usuario = await mVCDbContext1.Usuario.ToListAsync();
            return View(usuario);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> Add(AddUsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                var usuario = new Usuario
                {
                    Id = Guid.NewGuid(),
                    Nome = model.Nome,
                    Email = model.Email,
                    Senha = model.Senha,
                    Admin = model.Admin
                };
                await mVCDbContext1.Usuario.AddAsync(usuario);
                await mVCDbContext1.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var Usuario = await mVCDbContext1.Usuario.FirstOrDefaultAsync(x => x.Id == id);

            if (Usuario != null)
            {
                var viewModel = new UpdateUsuarioViewModel
                {
                    Id = Usuario.Id,
                    Nome = Usuario.Nome,
                    Email = Usuario.Email,
                    Senha = Usuario.Senha,
                    Admin = Usuario.Admin
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateUsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                var usuario = await mVCDbContext1.Usuario.FirstOrDefaultAsync(x => x.Id == model.Id);

                if (usuario != null)
                {
                    usuario.Nome = model.Nome;
                    usuario.Email = model.Email;
                    usuario.Senha = model.Senha;
                    usuario.Admin = model.Admin;

                    await mVCDbContext1.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateUsuarioViewModel model)
        {
            var Usuario = await mVCDbContext1.Usuario.FindAsync(model.Id);

            if (Usuario != null)
            {
                mVCDbContext1.Usuario.Remove(Usuario);
                await mVCDbContext1.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ObterUsuarioPorEmail(string email)
        {
            var usuario = mVCDbContext1.Usuario.FirstOrDefaultAsync(x => x.Email == email);
            return RedirectToAction("Index");
        }
    }
}

SGT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SGT.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        <header>
@*             <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid" style="background-color:burlywood">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SGT</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Index">Listar Tarefas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Add">Adicionar Tarefa</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav> *@
            <div class="menu">
                <nav class="main-nav">
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">SGT</a></li>
                        <li>
                            <a href="">Tarefas</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Tarefas" asp-action="Index">Listar Tarefas</a></li>
                                <li><a asp-area="" asp-controller="Tarefas" asp-action="Add">Adicionar Tarefa</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="">Usuários</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Listar Usuários</a></li>
                                <li><a asp-area="" asp-controller="Usuario" asp-action="Add">Adicionar Usuários</a></li>
@*                                 <li>
                                    <a href="#" title="Banco de Dados">Banco de Dados</a>

                                    <ul>
                                        <li><a href="#" title="MySQL">Prod</a></li>
                                        <li><a href="#" title="MariaDB">Homol </a></li>
                                    </ul>

                                </li>
 *@

                            </ul>
                        </li>
                        <li>
                            <a href="">Status</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Status" asp-action="Index">Listar Status</a></li>
                                <li><a asp-area="" asp-controller="Status" asp-action="Add">Adicionar Status</a></li>
                            </ul>
                        </li>
                        <li><a href="#" title="Fale Conosco">Fale Conosco</a></li>

                    </ul>

                </nav>
                <div class="mob-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <div class="overlay"></div>

            </div><!-- menu -->
        </header>
    </div>
    <div class="container">
        <main role="main" class="pb-3" style="background-color:darkgrey">
            @RenderBody()
        </main>
    </div>
    <div>
        <footer class="border-top footer text-muted" style="background-color:burlywood">
            <div class="container">
                &copy; 2024 - SGT - Sistema Gerenciador de Tarefas
            </div>
        </footer>
    </div>

    <script src="~/js/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SGT/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SGT.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        <header>
@*             <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid" style="background-color:burlywood">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SGT</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Index">Listar Tarefas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Add">Adicionar Tarefa</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav> *@


@*             <div class="menu">
                <nav class="main-nav">
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">SGT</a></li>
                        <li>
                            <a href="">Tarefas</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Tarefas" asp-action="Index">Listar Tarefas</a></li>
                                <li><a asp-area="" asp-controller="Tarefas" asp-action="Add">Adicionar Tarefa</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="">Usuários</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Listar Usuários</a></li>
                                <li><a asp-area="" asp-controller="Usuario" asp-action="Add">Adicionar Usuários</a></li>
                                <li>
                                    <a href="#" title="Banco de Dados">Banco de Dados</a>

                                    <ul>
                                        <li><a href="#" title="MySQL">Prod</a></li>
                                        <li><a href="#" title="MariaDB">Homol </a></li>
                                    </ul>

                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="">Status</a>
                            <ul>
                                <li><a asp-area="" asp-controller="Status" asp-action="Index">Listar Status</a></li>
                                <li><a asp-area="" asp-controller="Status" asp-action="Add">Adicionar Status</a></li>
                            </ul>
                        </li>
                        <li><a href="#" title="Fale Conosco">Fale Conosco</a></li>

                    </ul>

                </nav>
                <div class="mob-btn">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <div class="overlay"></div>

            </div><!-- menu -->
 *@

        </header>
    </div>
    <div class="container">
        <main role="main" class="pb-3" style="background-color:darkgrey">
            @RenderBody()
        </main>
    </div>
    <div>
        <footer class="border-top footer text-muted" style="background-color:burlywood">
            <div class="container">
                &copy; 2024 - SGT - Sistema Gerenciador de Tarefas
            </div>
        </footer>
    </div>

    <script src="~/js/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>